#ifndef __RISCV__
#define __RISCV__

#include "../common/cpu.h"

struct extension {
  int id;
  char* str;
};

#define RISCV_ISA_EXT_NAME_LEN_MAX 32
#define RISCV_ISA_EXT_BASE         26

// https://elixir.bootlin.com/linux/latest/source/arch/riscv/include/asm/hwcap.h
// This enum represent the logical ID for multi-letter RISC-V ISA extensions.
// The logical ID should start from RISCV_ISA_EXT_BASE
enum riscv_isa_ext_id {
  RISCV_ISA_EXT_SSCOFPMF = RISCV_ISA_EXT_BASE,
  RISCV_ISA_EXT_SSTC,
  RISCV_ISA_EXT_SVINVAL,
  RISCV_ISA_EXT_SVPBMT,
  RISCV_ISA_EXT_ZBB,
  RISCV_ISA_EXT_ZICBOM,
  RISCV_ISA_EXT_ZIHINTPAUSE,
  RISCV_ISA_EXT_SVNAPOT,
  RISCV_ISA_EXT_ZICBOZ,
  RISCV_ISA_EXT_SMAIA,
  RISCV_ISA_EXT_SSAIA,
  RISCV_ISA_EXT_ZBA,
  RISCV_ISA_EXT_ZBS,
  RISCV_ISA_EXT_ZICNTR,
  RISCV_ISA_EXT_ZICSR,
  RISCV_ISA_EXT_ZIFENCEI,
  RISCV_ISA_EXT_ZIHPM,
  RISCV_ISA_EXT_SMSTATEEN,
  RISCV_ISA_EXT_ZICOND,
  RISCV_ISA_EXT_ZBC,
  RISCV_ISA_EXT_ZBKB,
  RISCV_ISA_EXT_ZBKC,
  RISCV_ISA_EXT_ZBKX,
  RISCV_ISA_EXT_ZKND,
  RISCV_ISA_EXT_ZKNE,
  RISCV_ISA_EXT_ZKNH,
  RISCV_ISA_EXT_ZKR,
  RISCV_ISA_EXT_ZKSED,
  RISCV_ISA_EXT_ZKSH,
  RISCV_ISA_EXT_ZKT,
  RISCV_ISA_EXT_ZVBB,
  RISCV_ISA_EXT_ZVBC,
  RISCV_ISA_EXT_ZVKB,
  RISCV_ISA_EXT_ZVKG,
  RISCV_ISA_EXT_ZVKNED,
  RISCV_ISA_EXT_ZVKNHA,
  RISCV_ISA_EXT_ZVKNHB,
  RISCV_ISA_EXT_ZVKSED,
  RISCV_ISA_EXT_ZVKSH,
  RISCV_ISA_EXT_ZVKT,
  RISCV_ISA_EXT_ZFH,
  RISCV_ISA_EXT_ZFHMIN,
  RISCV_ISA_EXT_ZIHINTNTL,
  RISCV_ISA_EXT_ZVFH,
  RISCV_ISA_EXT_ZVFHMIN,
  RISCV_ISA_EXT_ZFA,
  RISCV_ISA_EXT_ZTSO,
  RISCV_ISA_EXT_ZACAS,
  RISCV_ISA_EXT_ZVE32X,
  RISCV_ISA_EXT_ZVE32F,
  RISCV_ISA_EXT_ZVE64X,
  RISCV_ISA_EXT_ZVE64F,
  RISCV_ISA_EXT_ZVE64D,
  RISCV_ISA_EXT_ZIMOP,
  RISCV_ISA_EXT_ZCA,
  RISCV_ISA_EXT_ZCB,
  RISCV_ISA_EXT_ZCD,
  RISCV_ISA_EXT_ZCF,
  RISCV_ISA_EXT_ZCMOP,
  RISCV_ISA_EXT_ZAWRS,
  RISCV_ISA_EXT_SVVPTC,
  RISCV_ISA_EXT_SMMPM,
  RISCV_ISA_EXT_SMNPM,
  RISCV_ISA_EXT_SSNPM,
  RISCV_ISA_EXT_ZABHA,
  RISCV_ISA_EXT_ZICCRSE,
  RISCV_ISA_EXT_SVADE,
  RISCV_ISA_EXT_SVADU,
  RISCV_ISA_EXT_ZFBFMIN,
  RISCV_ISA_EXT_ZVFBFMIN,
  RISCV_ISA_EXT_ZVFBFWMA,
  RISCV_ISA_EXT_ZAAMO,
  RISCV_ISA_EXT_ZALRSC,
  RISCV_ISA_EXT_ZICBOP,
  RISCV_ISA_EXT_IME,      // This is not in the kernel! but it was seen on a Muse Pi Pro board
  RISCV_ISA_EXT_ID_MAX
};

// https://five-embeddev.com/riscv-isa-manual/latest/preface.html#preface
// https://en.wikichip.org/wiki/risc-v/standard_extensions
// (Zicbop) https://github.com/riscv/riscv-CMOs/blob/master/cmobase/Zicbop.adoc
// https://raw.githubusercontent.com/riscv/riscv-CMOs/master/specifications/cmobase-v1.0.1.pdf
// https://www.kernel.org/doc/Documentation/devicetree/bindings/riscv/extensions.yaml
// (Ime) https://github.com/riscv/integrated-matrix-extension (not confirmed, just a guess...)
// Included all except for G
static const struct extension extension_list[] = {
  { 'i' - 'a', "(I) Integer Instruction Set" },
  { 'm' - 'a', "(M) Integer Multiplication and Division" },
  { 'a' - 'a', "(A) Atomic Instructions" },
  { 'f' - 'a', "(F) Single-Precision Floating-Point" },
  { 'd' - 'a', "(D) Double-Precision Floating-Point" },
  { 'q' - 'a', "(Q) Quad-Precision Floating-Point" },
  { 'l' - 'a', "(L) Decimal Floating-Point" },
  { 'c' - 'a', "(C) Compressed Instructions" },
  { 'b' - 'a', "(B) Double-Precision Floating-Point" },
  { 'j' - 'a', "(J) Dynamically Translated Languages" },
  { 't' - 'a', "(T) Transactional Memory" },
  { 'p' - 'a', "(P) Packed-SIMD Instructions" },
  { 'v' - 'a', "(V) Vector Operations" },
  { 'n' - 'a', "(N) User-Level Interrupts" },
  { 'h' - 'a', "(H) Hypervisor" },
  // multi-letter extensions
  { RISCV_ISA_EXT_SSCOFPMF,    "(Sscofpmf) Count OverFlow and Privilege Mode Filtering" },
  { RISCV_ISA_EXT_SSTC,        "(Sstc) S and VS level Time Compare" },
  { RISCV_ISA_EXT_SVINVAL,     "(Svinval) Fast TLB Invalidation" },
  { RISCV_ISA_EXT_SVPBMT,      "(Svpbmt) Page-based Memory Types" },
  { RISCV_ISA_EXT_ZBB,         "(Zbb) Basic bit-manipulation" },
  { RISCV_ISA_EXT_ZICBOM,      "(Zicbom) Cache Block Management Operations" },
  { RISCV_ISA_EXT_ZIHINTPAUSE, "(Zihintpause) Pause Hint" },
  { RISCV_ISA_EXT_SVNAPOT,     "(Svnapot) Naturally Aligned Power of Two Pages" },
  { RISCV_ISA_EXT_ZICBOZ,      "(Zicboz) Cache Block Zero Operations" },
  { RISCV_ISA_EXT_ZICBOP,      "(Zicbop) Cache Block Prefetch Operations" },
  { RISCV_ISA_EXT_SMAIA,       "(Smaia) Advanced Interrupt Architecture" },
  { RISCV_ISA_EXT_SSAIA,       "(Ssaia) Advanced Interrupt Architecture" },
  { RISCV_ISA_EXT_ZBA,         "(Zba) Address Generation" },
  { RISCV_ISA_EXT_ZBS,         "(Zbs) Single-bit Instructions" },
  { RISCV_ISA_EXT_ZICNTR,      "(Zicntr) Base Counters and Timers" },
  { RISCV_ISA_EXT_ZICSR,       "(Zicsr) Control and Status Register" },
  { RISCV_ISA_EXT_ZIFENCEI,    "(Zifencei) Instruction-Fetch Fence" },
  { RISCV_ISA_EXT_ZIHPM,       "(Zihpm) Hardware Performance Counters" },
  { RISCV_ISA_EXT_SMSTATEEN,   "(Smstateen) " },
  { RISCV_ISA_EXT_ZICOND,      "(Zicond) Integer Conditional Operations" },
  { RISCV_ISA_EXT_ZBC,         "(Zbc) Carry-Less Multiplication" },
  { RISCV_ISA_EXT_ZBKB,        "(Zbkb) " },
  { RISCV_ISA_EXT_ZBKC,        "(Zbkc) " },
  { RISCV_ISA_EXT_ZBKX,        "(Zbkx) " },
  { RISCV_ISA_EXT_ZKND,        "(Zknd) " },
  { RISCV_ISA_EXT_ZKNE,        "(Zkne) " },
  { RISCV_ISA_EXT_ZKNH,        "(Zknh) " },
  { RISCV_ISA_EXT_ZKR,         "(Zkr) " },
  { RISCV_ISA_EXT_ZKSED,       "(Zksed) " },
  { RISCV_ISA_EXT_ZKSH,        "(Zksh) " },
  { RISCV_ISA_EXT_ZKT,         "(Zkt) Data-Independent Execution Latency" },
  { RISCV_ISA_EXT_ZVBB,        "(Zvbb) " },
  { RISCV_ISA_EXT_ZVBC,        "(Zvbc) " },
  { RISCV_ISA_EXT_ZVKB,        "(Zvkb) " },
  { RISCV_ISA_EXT_ZVKG,        "(Zvkg) " },
  { RISCV_ISA_EXT_ZVKNED,      "(Zvkned) " },
  { RISCV_ISA_EXT_ZVKNHA,      "(Zvknha) " },
  { RISCV_ISA_EXT_ZVKNHB,      "(Zvknhb) " },
  { RISCV_ISA_EXT_ZVKSED,      "(Zvksed) " },
  { RISCV_ISA_EXT_ZVKSH,       "(Zvksh) " },
  { RISCV_ISA_EXT_ZVKT,        "(Zvkt) " },
  { RISCV_ISA_EXT_ZFH,         "(Zfh) " },
  { RISCV_ISA_EXT_ZFHMIN,      "(Zfhmin) " },
  { RISCV_ISA_EXT_ZIHINTNTL,   "(Zihintntl) " },
  { RISCV_ISA_EXT_ZVFH,        "(Zvfh) " },
  { RISCV_ISA_EXT_ZVFHMIN,     "(Zvfhmin) " },
  { RISCV_ISA_EXT_ZFA,         "(Zfa) " },
  { RISCV_ISA_EXT_ZTSO,        "(Ztso) " },
  { RISCV_ISA_EXT_ZACAS,       "(Zacas) " },
  { RISCV_ISA_EXT_ZVE32X,      "(Zve32x) Vector Extensions (i32)" },
  { RISCV_ISA_EXT_ZVE32F,      "(Zve32f) Vector Extensions (f32)" },
  { RISCV_ISA_EXT_ZVE64X,      "(Zve64x) Vector Extensions (i64)" },
  { RISCV_ISA_EXT_ZVE64F,      "(Zve64f) Vector Extensions (f64)" },
  { RISCV_ISA_EXT_ZVE64D,      "(Zve64d) Vector Extensions (???)" },
  { RISCV_ISA_EXT_ZIMOP,       "(Zimop) " },
  { RISCV_ISA_EXT_ZCA,         "(Zca) " },
  { RISCV_ISA_EXT_ZCB,         "(Zcb) " },
  { RISCV_ISA_EXT_ZCD,         "(Zcd) " },
  { RISCV_ISA_EXT_ZCF,         "(Zcf) " },
  { RISCV_ISA_EXT_ZCMOP,       "(Zcmop) " },
  { RISCV_ISA_EXT_ZAWRS,       "(Zawrs) " },
  { RISCV_ISA_EXT_SVVPTC,      "(Svvptc) " },
  { RISCV_ISA_EXT_SMMPM,       "(Smmpm) " },
  { RISCV_ISA_EXT_SMNPM,       "(Smnpm) " },
  { RISCV_ISA_EXT_SSNPM,       "(Ssnpm) " },
  { RISCV_ISA_EXT_ZABHA,       "(Zabha) " },
  { RISCV_ISA_EXT_ZICCRSE,     "(Ziccrse) " },
  { RISCV_ISA_EXT_SVADE,       "(Svade) " },
  { RISCV_ISA_EXT_SVADU,       "(Svadu) " },
  { RISCV_ISA_EXT_ZFBFMIN,     "(Zfbfmin) " },
  { RISCV_ISA_EXT_ZVFBFMIN,    "(Zvfbfmin) " },
  { RISCV_ISA_EXT_ZVFBFWMA,    "(Zvfbfwma) " },
  { RISCV_ISA_EXT_ZAAMO,       "(Zaamo) " },
  { RISCV_ISA_EXT_ZALRSC,      "(Zalrsc) " },
  { RISCV_ISA_EXT_ZICBOP,      "(Zicbop) " },
  { RISCV_ISA_EXT_IME,         "(Ime) Integrated Matrix Extension" },
};

struct cpuInfo* get_cpu_info(void);
char* get_str_topology(struct cpuInfo* cpu, struct topology* topo);
char* get_str_extensions(struct cpuInfo* cpu);
uint32_t get_num_extensions(bool* mask);
void print_debug(struct cpuInfo* cpu);

#endif
