#ifndef __RISCV__
#define __RISCV__

#include "../common/cpu.h"

struct extension {
  int id;
  char* str;
};

#define RISCV_ISA_EXT_NAME_LEN_MAX 32
#define RISCV_ISA_EXT_BASE         26

// https://elixir.bootlin.com/linux/latest/source/arch/riscv/include/asm/hwcap.h
// This enum represent the logical ID for multi-letter RISC-V ISA extensions.
// The logical ID should start from RISCV_ISA_EXT_BASE
enum riscv_isa_ext_id {
  RISCV_ISA_EXT_SSCOFPMF = RISCV_ISA_EXT_BASE,
  RISCV_ISA_EXT_SSTC,
  RISCV_ISA_EXT_SVINVAL,
  RISCV_ISA_EXT_SVPBMT,
  RISCV_ISA_EXT_ZBB,
  RISCV_ISA_EXT_ZICBOM,
  RISCV_ISA_EXT_ZIHINTPAUSE,
  RISCV_ISA_EXT_SVNAPOT,
  RISCV_ISA_EXT_ZICBOZ,
  RISCV_ISA_EXT_SMAIA,
  RISCV_ISA_EXT_SSAIA,
  RISCV_ISA_EXT_ZBA,
  RISCV_ISA_EXT_ZBS,
  RISCV_ISA_EXT_ZICNTR,
  RISCV_ISA_EXT_ZICSR,
  RISCV_ISA_EXT_ZIFENCEI,
  RISCV_ISA_EXT_ZIHPM,
  RISCV_ISA_EXT_SMSTATEEN,
  RISCV_ISA_EXT_ZICOND,
  RISCV_ISA_EXT_ZBC,
  RISCV_ISA_EXT_ZBKB,
  RISCV_ISA_EXT_ZBKC,
  RISCV_ISA_EXT_ZBKX,
  RISCV_ISA_EXT_ZKND,
  RISCV_ISA_EXT_ZKNE,
  RISCV_ISA_EXT_ZKNH,
  RISCV_ISA_EXT_ZKR,
  RISCV_ISA_EXT_ZKSED,
  RISCV_ISA_EXT_ZKSH,
  RISCV_ISA_EXT_ZKT,
  RISCV_ISA_EXT_ZVBB,
  RISCV_ISA_EXT_ZVBC,
  RISCV_ISA_EXT_ZVKB,
  RISCV_ISA_EXT_ZVKG,
  RISCV_ISA_EXT_ZVKNED,
  RISCV_ISA_EXT_ZVKNHA,
  RISCV_ISA_EXT_ZVKNHB,
  RISCV_ISA_EXT_ZVKSED,
  RISCV_ISA_EXT_ZVKSH,
  RISCV_ISA_EXT_ZVKT,
  RISCV_ISA_EXT_ZFH,
  RISCV_ISA_EXT_ZFHMIN,
  RISCV_ISA_EXT_ZIHINTNTL,
  RISCV_ISA_EXT_ZVFH,
  RISCV_ISA_EXT_ZVFHMIN,
  RISCV_ISA_EXT_ZFA,
  RISCV_ISA_EXT_ZTSO,
  RISCV_ISA_EXT_ZACAS,
  RISCV_ISA_EXT_ZVE32X,
  RISCV_ISA_EXT_ZVE32F,
  RISCV_ISA_EXT_ZVE64X,
  RISCV_ISA_EXT_ZVE64F,
  RISCV_ISA_EXT_ZVE64D,
  RISCV_ISA_EXT_ZIMOP,
  RISCV_ISA_EXT_ZCA,
  RISCV_ISA_EXT_ZCB,
  RISCV_ISA_EXT_ZCD,
  RISCV_ISA_EXT_ZCF,
  RISCV_ISA_EXT_ZCMOP,
  RISCV_ISA_EXT_ZAWRS,
  RISCV_ISA_EXT_SVVPTC,
  RISCV_ISA_EXT_SMMPM,
  RISCV_ISA_EXT_SMNPM,
  RISCV_ISA_EXT_SSNPM,
  RISCV_ISA_EXT_ZABHA,
  RISCV_ISA_EXT_ZICCRSE,
  RISCV_ISA_EXT_SVADE,
  RISCV_ISA_EXT_SVADU,
  RISCV_ISA_EXT_ZFBFMIN,
  RISCV_ISA_EXT_ZVFBFMIN,
  RISCV_ISA_EXT_ZVFBFWMA,
  RISCV_ISA_EXT_ZAAMO,
  RISCV_ISA_EXT_ZALRSC,
  RISCV_ISA_EXT_ZICBOP,
  RISCV_ISA_EXT_IME,
  RISCV_ISA_EXT_ID_MAX
};

// https://five-embeddev.com/riscv-isa-manual/latest/preface.html#preface
// https://en.wikichip.org/wiki/risc-v/standard_extensions
// (Zicbop) https://github.com/riscv/riscv-CMOs/blob/master/cmobase/Zicbop.adoc
// https://raw.githubusercontent.com/riscv/riscv-CMOs/master/specifications/cmobase-v1.0.1.pdf
// Included all except for G
static const struct extension extension_list[] = {
  { 'i' - 'a', "(I) Integer Instruction Set" },
  { 'm' - 'a', "(M) Integer Multiplication and Division" },
  { 'a' - 'a', "(A) Atomic Instructions" },
  { 'f' - 'a', "(F) Single-Precision Floating-Point" },
  { 'd' - 'a', "(D) Double-Precision Floating-Point" },
  { 'q' - 'a', "(Q) Quad-Precision Floating-Point" },
  { 'l' - 'a', "(L) Decimal Floating-Point" },
  { 'c' - 'a', "(C) Compressed Instructions" },
  { 'b' - 'a', "(B) Double-Precision Floating-Point" },
  { 'j' - 'a', "(J) Dynamically Translated Languages" },
  { 't' - 'a', "(T) Transactional Memory" },
  { 'p' - 'a', "(P) Packed-SIMD Instructions" },
  { 'v' - 'a', "(V) Vector Operations" },
  { 'n' - 'a', "(N) User-Level Interrupts" },
  { 'h' - 'a', "(H) Hypervisor" },
  // multi-letter extensions
  { RISCV_ISA_EXT_SSCOFPMF,    "(Sscofpmf) Count OverFlow and Privilege Mode Filtering" },
  { RISCV_ISA_EXT_SSTC,        "(Sstc) S and VS level Time Compare" },
  { RISCV_ISA_EXT_SVINVAL,     "(Svinval) Fast TLB Invalidation" },
  { RISCV_ISA_EXT_SVPBMT,      "(Svpbmt) Page-based Memory Types" },
  { RISCV_ISA_EXT_ZBB,         "(Zbb) Basic bit-manipulation" },
  { RISCV_ISA_EXT_ZICBOM,      "(Zicbom) Cache Block Management Operations" },
  { RISCV_ISA_EXT_ZIHINTPAUSE, "(Zihintpause) Pause Hint" },
  { RISCV_ISA_EXT_SVNAPOT,     "(Svnapot) Naturally Aligned Power of Two Pages" },
  { RISCV_ISA_EXT_ZICBOZ,      "(Zicboz) Cache Block Zero Operations" },
  { RISCV_ISA_EXT_ZICBOP,      "(Zicbop) Cache Block Prefetch Operations" },
  { RISCV_ISA_EXT_SMAIA,       "(Smaia) Advanced Interrupt Architecture" },
  { RISCV_ISA_EXT_SSAIA,       "(Ssaia) Advanced Interrupt Architecture" },
  { RISCV_ISA_EXT_ZBA,         "(Zba) Address Generation" },
  { RISCV_ISA_EXT_ZBS,         "(Zbs) Single-bit Instructions" },
  { RISCV_ISA_EXT_ZICNTR,      "(Zicntr) Base Counters and Timers" },
  { RISCV_ISA_EXT_ZICSR,       "(Zicsr) Control and Status Register" },
  { RISCV_ISA_EXT_ZIFENCEI,    "(Zifencei) Instruction-Fetch Fence" },
  { RISCV_ISA_EXT_ZIHPM,       "(Zihpm) Hardware Performance Counters" },
  { RISCV_ISA_EXT_SMSTATEEN,   "(smstateen) " },
  { RISCV_ISA_EXT_ZICOND,      "(zicond) " },
  { RISCV_ISA_EXT_ZBC,         "(zbc) " },
  { RISCV_ISA_EXT_ZBKB,        "(zbkb) " },
  { RISCV_ISA_EXT_ZBKC,        "(zbkc) " },
  { RISCV_ISA_EXT_ZBKX,        "(zbkx) " },
  { RISCV_ISA_EXT_ZKND,        "(zknd) " },
  { RISCV_ISA_EXT_ZKNE,        "(zkne) " },
  { RISCV_ISA_EXT_ZKNH,        "(zknh) " },
  { RISCV_ISA_EXT_ZKR,         "(zkr) " },
  { RISCV_ISA_EXT_ZKSED,       "(zksed) " },
  { RISCV_ISA_EXT_ZKSH,        "(zksh) " },
  { RISCV_ISA_EXT_ZKT,         "(zkt) " },
  { RISCV_ISA_EXT_ZVBB,        "(zvbb) " },
  { RISCV_ISA_EXT_ZVBC,        "(zvbc) " },
  { RISCV_ISA_EXT_ZVKB,        "(zvkb) " },
  { RISCV_ISA_EXT_ZVKG,        "(zvkg) " },
  { RISCV_ISA_EXT_ZVKNED,      "(zvkned) " },
  { RISCV_ISA_EXT_ZVKNHA,      "(zvknha) " },
  { RISCV_ISA_EXT_ZVKNHB,      "(zvknhb) " },
  { RISCV_ISA_EXT_ZVKSED,      "(zvksed) " },
  { RISCV_ISA_EXT_ZVKSH,       "(zvksh) " },
  { RISCV_ISA_EXT_ZVKT,        "(zvkt) " },
  { RISCV_ISA_EXT_ZFH,         "(zfh) " },
  { RISCV_ISA_EXT_ZFHMIN,      "(zfhmin) " },
  { RISCV_ISA_EXT_ZIHINTNTL,   "(zihintntl) " },
  { RISCV_ISA_EXT_ZVFH,        "(zvfh) " },
  { RISCV_ISA_EXT_ZVFHMIN,     "(zvfhmin) " },
  { RISCV_ISA_EXT_ZFA,         "(zfa) " },
  { RISCV_ISA_EXT_ZTSO,        "(ztso) " },
  { RISCV_ISA_EXT_ZACAS,       "(zacas) " },
  { RISCV_ISA_EXT_ZVE32X,      "(zve32x) " },
  { RISCV_ISA_EXT_ZVE32F,      "(zve32f) " },
  { RISCV_ISA_EXT_ZVE64X,      "(zve64x) " },
  { RISCV_ISA_EXT_ZVE64F,      "(zve64f) " },
  { RISCV_ISA_EXT_ZVE64D,      "(zve64d) " },
  { RISCV_ISA_EXT_ZIMOP,       "(zimop) " },
  { RISCV_ISA_EXT_ZCA,         "(zca) " },
  { RISCV_ISA_EXT_ZCB,         "(zcb) " },
  { RISCV_ISA_EXT_ZCD,         "(zcd) " },
  { RISCV_ISA_EXT_ZCF,         "(zcf) " },
  { RISCV_ISA_EXT_ZCMOP,       "(zcmop) " },
  { RISCV_ISA_EXT_ZAWRS,       "(zawrs) " },
  { RISCV_ISA_EXT_SVVPTC,      "(svvptc) " },
  { RISCV_ISA_EXT_SMMPM,       "(smmpm) " },
  { RISCV_ISA_EXT_SMNPM,       "(smnpm) " },
  { RISCV_ISA_EXT_SSNPM,       "(ssnpm) " },
  { RISCV_ISA_EXT_ZABHA,       "(zabha) " },
  { RISCV_ISA_EXT_ZICCRSE,     "(ziccrse) " },
  { RISCV_ISA_EXT_SVADE,       "(svade) " },
  { RISCV_ISA_EXT_SVADU,       "(svadu) " },
  { RISCV_ISA_EXT_ZFBFMIN,     "(zfbfmin) " },
  { RISCV_ISA_EXT_ZVFBFMIN,    "(zvfbfmin) " },
  { RISCV_ISA_EXT_ZVFBFWMA,    "(zvfbfwma) " },
  { RISCV_ISA_EXT_ZAAMO,       "(zaamo) " },
  { RISCV_ISA_EXT_ZALRSC,      "(zalrsc) " },
  { RISCV_ISA_EXT_ZICBOP,      "(zicbop) " },
  { RISCV_ISA_EXT_IME,         "(ime) Integrated Matrix Extension" },
};

struct cpuInfo* get_cpu_info(void);
char* get_str_topology(struct cpuInfo* cpu, struct topology* topo);
char* get_str_extensions(struct cpuInfo* cpu);
uint32 get_num_extensions(bool* mask);
void print_debug(struct cpuInfo* cpu);

#endif
